### PR TITLE
passphrase parameter can be added to config file.

### PR DESCRIPTION
**Pull request by kuzakabe**
added "passphrase" parameter to config

### CODE REVIEW

**Comment by lukasz-wronski** [comment]
What is the diffrence between password and passphrase?

**Comment by kuzakabe** [comment]
Password is for ftp/sftp user.
Passphrase is for private key.

Even now(v3.0.1), we can connect to servers with a non-protected private key.
However, cannot connect with a passphrase-protected private key.

**Comment by tneu** [comment]
While we're at it, can i suggest to add "agent" aswell?
Not everyone wants to have an either unphrased privatekey or the phrase in plain text laying around on a filesystem.

As per npn ssh2 readme:

"agent - string - Path to ssh-agent's UNIX socket for ssh-agent-based user authentication. Windows users: set to 'pageant' for authenticating with Pageant or (actual) path to a cygwin "UNIX socket." Default: (none)"

I added the agent option with "pageant" value and it works a charm on my Win10 box.

**Comment by barisusakli** [comment]
+1

**Comment by anatooly** [comment]
I'm test now, for me this work correct, before this on logs file I see connect & upload but nothing changes, now all right. Waiting merge.

**Pull request merged**
