### PR TITLE
Fixed bug where vscode crash/stack on Collecting local files list

### PR DESCRIPTION
**Pull request by davbizz**
Hi i have fix this bug  https://github.com/lukasz-wronski/vscode-ftp-sync/issues/85 and https://github.com/lukasz-wronski/vscode-ftp-sync/issues/48 with a small workaround. Maybe it col be done better but for now this is working very fine.

### CODE REVIEW

**Comment by blakiba** [comment]
thanks

**Comment by kalieye** [comment]
if you fix the conflicts i will gladly merge this
thanks

**Comment by davbizz** [comment]
Hi the first time i have send the pull there was no conflict. I will try to resolve it a soon as possible but i haven't much time.

**Comment by davbizz** [comment]
I have solve all conflicts !!!!

**Comment by kalieye** [comment]
thank you!

**Pull request merged**
