### PR TITLE
Generated File Watching

### PR DESCRIPTION
**Pull request by jsmilovic**
This adds a file watcher for generated files to get auto uploaded.  Supports three parameters

    "generatedFiles": {
        "uploadOnSave": true,
        "path": "/stylus",
        "extensionsToInclude": [".js", ".styl"]
    }

Should solve several of the issues currently in github

### CODE REVIEW

**Comment by jsmilovic** [comment]
Addresses #83 #71 #65

**Comment by sagive** [comment]
Usage example? Where should we add this? does this goes to ftp-sync json file?

**Comment by brouwerQ** [comment]
On GitHub it says that this is available in version 0.3.3, but in the Visual Studio Marketplace it only goes to 0.3.2. When will 0.3.3 be available?

**Comment by danielpost** [comment]
Can you elaborate on what to enter in path? My SCSS folder is src/scss/ and my style.css is in the project root but I can't get it to work.

**Comment by ZanderBrown** [comment]
Having looked at the code it seems to watch for changes to any file in `[WORKSPACE]/'generatedFiles.path'/**`
so i guess if your generated file is in the root you would need to set it to an empty string

**Comment by palashjhabak** [comment]
As this update is not available in the extension marketplace yet, you can manually install and use it.

**Comment by SinZ163** [comment]
@jsmilovic Still not available on the marketplace, been months since this was added to 0.33, and still not available

**Comment by jsmilovic** [comment]
@SinZ163 ok I've gotten the keys to the kingdom (so to speak) so I was able to publish this to the marketplace myself.  Thanks for the patience, sorry for the wait!  Let me know if you have any problems with it after updating

**Comment by lynnchen1020** [comment]
Hi, I use gulp to compile sass -> css, I still can't auto save generated files, 
Can anyone help me to see is there any problem with my settings?  Thanks in advance. 

My settings are as below:

=== local folders ===
src/
| - /sass

**generated folder** 
dist/
| - /css

=== remote folders ===
./
| - /css


** my ftp-sync.json **
"generatedFiles": {
    "uploadOnSave": true,
    "path": "./dist/css",
    "extensionsToInclude": [".css"]
}

**Comment by estoj** [comment]
@jsmilovic Could you be more specific on how to use this feature ? I don't get why I should add the extensions ".scss" when I want to upload the ".css" (which is in another directory). Thanks !

**Pull request merged**
