### PR TITLE
Enable FTP with SSL support

### PR DESCRIPTION
**Pull request by hajekj**
This option is required in order to have FTP with SSL support.

Fixes https://github.com/lukasz-wronski/vscode-ftp-sync/issues/30

### CODE REVIEW

**Comment by lukasz-wronski** [comment]
Hi, thank you for a pull request. It's very helpful for me that you are engaged in this project too. What I'd like to ask you is to apply to your fix the same indentation as in original file. Right now I cant really check what was changed because it looks like the whole file was rewritten.

**Comment by hajekj** [comment]
Generally, I think that the formatting is screwed up in the file, all that was changed is following:

1. Added `secure: false,` to `defaultConfig`
2. Added `secure: config.secure,` to `getSyncConfig`

**Comment by Nighthawk22** [comment]
Hi @hajekj 
This pull request is really helpfull. Changed my local files according to your pull request.
It would also be really awesome to add the secureOptions option so you could also ignore invalid certs.

**Comment by hajekj** [comment]
@Nighthawk22 That is a great idea, I will see about adding that into this PR.

**Comment by michalhudecek** [comment]
@hajekj @lukasz-wronski Can you please finish this pull request? I see it's just a small change. It would be very helpful! Thanks a lot.

**Comment by hajekj** [comment]
Sorry, don't have permissions on the repo.

**Comment by michalhudecek** [comment]
@lukasz-wronski Can't you give permissions to someone else as well? The latest update of this repo is from January :( It's a pitty.

**Comment by hajekj** [comment]
We could fork the repo and make our own official release from this.. As a plan B

**Comment by michalhudecek** [comment]
Lukasz is looking for collaborators https://github.com/lukasz-wronski/vscode-ftp-sync/issues/96. I think you can just ask him to get access

**Comment by lukasz-wronski** [comment]
https://github.com/lukasz-wronski/vscode-ftp-sync/issues/96

pt., 21.10.2016, 23:46 użytkownik Jan Hajek <notifications@github.com>
napisał:

**Pull request merged**
