### PR TITLE
Various enhancements (SCP Support, bug fixes, list command)

### PR DESCRIPTION
**Pull request by valepu**
Various enhancements:
- Added SCP support (using scp2, which uses ssh2 behind just like this plugin)
- Updated lodash to 4.11.1 (doesn't have the _.any method anymore, it uses _.some instead)
- Added list command and various bug fixes (I merged from https://github.com/tianyishen/vscode-ftp-sync before making a pull request)

All the new plugin features have been tested manually
Requires a npm install to work

### CODE REVIEW

**Comment by valepu** [comment]
Solves https://github.com/lukasz-wronski/vscode-ftp-sync/issues/234

**Comment by valepu** [comment]
might still need some polishing but even as it is now it works

**Comment by dfarley1** [comment]
Looks like this is somewhat of a dead repo... Pity because it's such a great plugin.  Maybe you should upload your fixed version to VSCode?

**Comment by valepu** [comment]
I'm not sure i'll have time to maintain it but i'll consider the idea

**Comment by hajekj** [comment]
I have merged the change, however I don't have any permission to publish the new versio nof the plugin. Maybe you could take a look at at https://github.com/mkloubert/vscode-remote-workspace/ which is much more active and implements the latest VS Code features like virtual filesystem.

**Pull request merged**
